language: java


jdk:
  - oraclejdk8

install:
  - echo 'Nix zu installieren'

script:
  - mvn -P prepareProject clean validate
  - mvn clean install

after_script:
  - echo `ls ${HOME}/.m2/repository/myDepGroup/myDepArtifactID/1.2.3/`
  - echo `ls /home/travis/.m2/repository/myDepGroup/myDepArtifactID/1.2.3/`

after_success:
  - bash <(curl -s https://codecov.io/bash)
